// This file was generated by Mendix Studio Pro.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package testmodule.proxies;

public class DataObject
{
	private final com.mendix.systemwideinterfaces.core.IMendixObject dataObjectMendixObject;

	private final com.mendix.systemwideinterfaces.core.IContext context;

	/**
	 * Internal name of this entity
	 */
	public static final java.lang.String entityName = "TestModule.DataObject";

	/**
	 * Enum describing members of this entity
	 */
	public enum MemberNames
	{
		name("name"),
		dept("dept"),
		sal("sal"),
		DataObject_Asso_DataObject("TestModule.DataObject_Asso_DataObject");

		private java.lang.String metaName;

		MemberNames(java.lang.String s)
		{
			metaName = s;
		}

		@java.lang.Override
		public java.lang.String toString()
		{
			return metaName;
		}
	}

	public DataObject(com.mendix.systemwideinterfaces.core.IContext context)
	{
		this(context, com.mendix.core.Core.instantiate(context, "TestModule.DataObject"));
	}

	protected DataObject(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject dataObjectMendixObject)
	{
		if (dataObjectMendixObject == null)
			throw new java.lang.IllegalArgumentException("The given object cannot be null.");
		if (!com.mendix.core.Core.isSubClassOf("TestModule.DataObject", dataObjectMendixObject.getType()))
			throw new java.lang.IllegalArgumentException("The given object is not a TestModule.DataObject");

		this.dataObjectMendixObject = dataObjectMendixObject;
		this.context = context;
	}

	/**
	 * @deprecated Use 'DataObject.load(IContext, IMendixIdentifier)' instead.
	 */
	@java.lang.Deprecated
	public static testmodule.proxies.DataObject initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		return testmodule.proxies.DataObject.load(context, mendixIdentifier);
	}

	/**
	 * Initialize a proxy using context (recommended). This context will be used for security checking when the get- and set-methods without context parameters are called.
	 * The get- and set-methods with context parameter should be used when for instance sudo access is necessary (IContext.createSudoClone() can be used to obtain sudo access).
	 */
	public static testmodule.proxies.DataObject initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject mendixObject)
	{
		return new testmodule.proxies.DataObject(context, mendixObject);
	}

	public static testmodule.proxies.DataObject load(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		com.mendix.systemwideinterfaces.core.IMendixObject mendixObject = com.mendix.core.Core.retrieveId(context, mendixIdentifier);
		return testmodule.proxies.DataObject.initialize(context, mendixObject);
	}

	public static java.util.List<testmodule.proxies.DataObject> load(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String xpathConstraint) throws com.mendix.core.CoreException
	{
		java.util.List<testmodule.proxies.DataObject> result = new java.util.ArrayList<testmodule.proxies.DataObject>();
		for (com.mendix.systemwideinterfaces.core.IMendixObject obj : com.mendix.core.Core.retrieveXPathQuery(context, "//TestModule.DataObject" + xpathConstraint))
			result.add(testmodule.proxies.DataObject.initialize(context, obj));
		return result;
	}

	/**
	 * Commit the changes made on this proxy object.
	 */
	public final void commit() throws com.mendix.core.CoreException
	{
		com.mendix.core.Core.commit(context, getMendixObject());
	}

	/**
	 * Commit the changes made on this proxy object using the specified context.
	 */
	public final void commit(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		com.mendix.core.Core.commit(context, getMendixObject());
	}

	/**
	 * Delete the object.
	 */
	public final void delete()
	{
		com.mendix.core.Core.delete(context, getMendixObject());
	}

	/**
	 * Delete the object using the specified context.
	 */
	public final void delete(com.mendix.systemwideinterfaces.core.IContext context)
	{
		com.mendix.core.Core.delete(context, getMendixObject());
	}
	/**
	 * @return value of name
	 */
	public final java.lang.String getname()
	{
		return getname(getContext());
	}

	/**
	 * @param context
	 * @return value of name
	 */
	public final java.lang.String getname(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.name.toString());
	}

	/**
	 * Set value of name
	 * @param name
	 */
	public final void setname(java.lang.String name)
	{
		setname(getContext(), name);
	}

	/**
	 * Set value of name
	 * @param context
	 * @param name
	 */
	public final void setname(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String name)
	{
		getMendixObject().setValue(context, MemberNames.name.toString(), name);
	}

	/**
	 * @return value of dept
	 */
	public final java.lang.String getdept()
	{
		return getdept(getContext());
	}

	/**
	 * @param context
	 * @return value of dept
	 */
	public final java.lang.String getdept(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.dept.toString());
	}

	/**
	 * Set value of dept
	 * @param dept
	 */
	public final void setdept(java.lang.String dept)
	{
		setdept(getContext(), dept);
	}

	/**
	 * Set value of dept
	 * @param context
	 * @param dept
	 */
	public final void setdept(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String dept)
	{
		getMendixObject().setValue(context, MemberNames.dept.toString(), dept);
	}

	/**
	 * @return value of sal
	 */
	public final java.lang.Integer getsal()
	{
		return getsal(getContext());
	}

	/**
	 * @param context
	 * @return value of sal
	 */
	public final java.lang.Integer getsal(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.Integer) getMendixObject().getValue(context, MemberNames.sal.toString());
	}

	/**
	 * Set value of sal
	 * @param sal
	 */
	public final void setsal(java.lang.Integer sal)
	{
		setsal(getContext(), sal);
	}

	/**
	 * Set value of sal
	 * @param context
	 * @param sal
	 */
	public final void setsal(com.mendix.systemwideinterfaces.core.IContext context, java.lang.Integer sal)
	{
		getMendixObject().setValue(context, MemberNames.sal.toString(), sal);
	}

	/**
	 * @return value of DataObject_Asso_DataObject
	 */
	public final testmodule.proxies.Asso_DataObject getDataObject_Asso_DataObject() throws com.mendix.core.CoreException
	{
		return getDataObject_Asso_DataObject(getContext());
	}

	/**
	 * @param context
	 * @return value of DataObject_Asso_DataObject
	 */
	public final testmodule.proxies.Asso_DataObject getDataObject_Asso_DataObject(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		testmodule.proxies.Asso_DataObject result = null;
		com.mendix.systemwideinterfaces.core.IMendixIdentifier identifier = getMendixObject().getValue(context, MemberNames.DataObject_Asso_DataObject.toString());
		if (identifier != null)
			result = testmodule.proxies.Asso_DataObject.load(context, identifier);
		return result;
	}

	/**
	 * Set value of DataObject_Asso_DataObject
	 * @param dataobject_asso_dataobject
	 */
	public final void setDataObject_Asso_DataObject(testmodule.proxies.Asso_DataObject dataobject_asso_dataobject)
	{
		setDataObject_Asso_DataObject(getContext(), dataobject_asso_dataobject);
	}

	/**
	 * Set value of DataObject_Asso_DataObject
	 * @param context
	 * @param dataobject_asso_dataobject
	 */
	public final void setDataObject_Asso_DataObject(com.mendix.systemwideinterfaces.core.IContext context, testmodule.proxies.Asso_DataObject dataobject_asso_dataobject)
	{
		if (dataobject_asso_dataobject == null)
			getMendixObject().setValue(context, MemberNames.DataObject_Asso_DataObject.toString(), null);
		else
			getMendixObject().setValue(context, MemberNames.DataObject_Asso_DataObject.toString(), dataobject_asso_dataobject.getMendixObject().getId());
	}

	/**
	 * @return the IMendixObject instance of this proxy for use in the Core interface.
	 */
	public final com.mendix.systemwideinterfaces.core.IMendixObject getMendixObject()
	{
		return dataObjectMendixObject;
	}

	/**
	 * @return the IContext instance of this proxy, or null if no IContext instance was specified at initialization.
	 */
	public final com.mendix.systemwideinterfaces.core.IContext getContext()
	{
		return context;
	}

	@java.lang.Override
	public boolean equals(Object obj)
	{
		if (obj == this)
			return true;

		if (obj != null && getClass().equals(obj.getClass()))
		{
			final testmodule.proxies.DataObject that = (testmodule.proxies.DataObject) obj;
			return getMendixObject().equals(that.getMendixObject());
		}
		return false;
	}

	@java.lang.Override
	public int hashCode()
	{
		return getMendixObject().hashCode();
	}

	/**
	 * @return String name of this class
	 */
	public static java.lang.String getType()
	{
		return "TestModule.DataObject";
	}

	/**
	 * @return String GUID from this object, format: ID_0000000000
	 * @deprecated Use getMendixObject().getId().toLong() to get a unique identifier for this object.
	 */
	@java.lang.Deprecated
	public java.lang.String getGUID()
	{
		return "ID_" + getMendixObject().getId().toLong();
	}
}
