// This file was generated by Mendix Studio Pro.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package testmodule.proxies.microflows;

import java.util.HashMap;
import java.util.Map;
import com.mendix.core.Core;
import com.mendix.core.CoreException;
import com.mendix.systemwideinterfaces.MendixRuntimeException;
import com.mendix.systemwideinterfaces.core.IContext;

public class Microflows
{
	// These are the microflows for the TestModule module
	public static void sub_CreateEmail(IContext context, emailtemplate.proxies.EmailTemplate _emailTemplate)
	{
		Map<java.lang.String, Object> params = new HashMap<>();
		params.put("EmailTemplate", _emailTemplate == null ? null : _emailTemplate.getMendixObject());
		Core.microflowCall("TestModule.Sub_CreateEmail").withParams(params).execute(context);
	}
	public static void tEST_CreateTestData(IContext context)
	{
		Map<java.lang.String, Object> params = new HashMap<>();
		Core.microflowCall("TestModule.TEST_CreateTestData").withParams(params).execute(context);
	}
}