// This file was generated by Mendix Studio Pro.
//
// WARNING: Only the following code will be retained when actions are regenerated:
// - the import list
// - the code between BEGIN USER CODE and END USER CODE
// - the code between BEGIN EXTRA CODE and END EXTRA CODE
// Other code you write will be lost the next time you deploy the project.
// Special characters, e.g., é, ö, à, etc. are supported in comments.

package mxmodelreflection.actions;

import com.mendix.systemwideinterfaces.core.IContext;
import com.mendix.webui.CustomJavaAction;
import com.mendix.systemwideinterfaces.core.IMendixObject;
import mxmodelreflection.proxies.MxObjectEnumCaptions;
import java.util.stream.Collectors;

public class JA_EnumValueLanguages extends CustomJavaAction<java.lang.String>
{
	private IMendixObject __objectEnumValue;
	private mxmodelreflection.proxies.MxObjectEnumValue objectEnumValue;

	public JA_EnumValueLanguages(IContext context, IMendixObject objectEnumValue)
	{
		super(context);
		this.__objectEnumValue = objectEnumValue;
	}

	@java.lang.Override
	public java.lang.String executeAction() throws Exception
	{
		this.objectEnumValue = this.__objectEnumValue == null ? null : mxmodelreflection.proxies.MxObjectEnumValue.initialize(getContext(), __objectEnumValue);

		// BEGIN USER CODE
		if (objectEnumValue == null) {
			return null;
		} else {
			return objectEnumValue.getCaptions().stream().map(MxObjectEnumCaptions::getLanguageCode).collect(Collectors.joining(", "));
		}
		// END USER CODE
	}

	/**
	 * Returns a string representation of this action
	 * @return a string representation of this action
	 */
	@java.lang.Override
	public java.lang.String toString()
	{
		return "JA_EnumValueLanguages";
	}

	// BEGIN EXTRA CODE
	// END EXTRA CODE
}
