// This file was generated by Mendix Studio Pro.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package migrationutility.proxies;

public class DataStats_Before
{
	private final com.mendix.systemwideinterfaces.core.IMendixObject dataStats_BeforeMendixObject;

	private final com.mendix.systemwideinterfaces.core.IContext context;

	/**
	 * Internal name of this entity
	 */
	public static final java.lang.String entityName = "MigrationUtility.DataStats_Before";

	/**
	 * Enum describing members of this entity
	 */
	public enum MemberNames
	{
		ECAccounts("ECAccounts"),
		ECEmails("ECEmails"),
		ECTemplates("ECTemplates"),
		ECErrorLogs("ECErrorLogs"),
		ETAccounts("ETAccounts"),
		ETEmails("ETEmails"),
		ETTemplates("ETTemplates"),
		ETErrorLogs("ETErrorLogs");

		private java.lang.String metaName;

		MemberNames(java.lang.String s)
		{
			metaName = s;
		}

		@java.lang.Override
		public java.lang.String toString()
		{
			return metaName;
		}
	}

	public DataStats_Before(com.mendix.systemwideinterfaces.core.IContext context)
	{
		this(context, com.mendix.core.Core.instantiate(context, "MigrationUtility.DataStats_Before"));
	}

	protected DataStats_Before(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject dataStats_BeforeMendixObject)
	{
		if (dataStats_BeforeMendixObject == null)
			throw new java.lang.IllegalArgumentException("The given object cannot be null.");
		if (!com.mendix.core.Core.isSubClassOf("MigrationUtility.DataStats_Before", dataStats_BeforeMendixObject.getType()))
			throw new java.lang.IllegalArgumentException("The given object is not a MigrationUtility.DataStats_Before");

		this.dataStats_BeforeMendixObject = dataStats_BeforeMendixObject;
		this.context = context;
	}

	/**
	 * @deprecated Use 'DataStats_Before.load(IContext, IMendixIdentifier)' instead.
	 */
	@java.lang.Deprecated
	public static migrationutility.proxies.DataStats_Before initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		return migrationutility.proxies.DataStats_Before.load(context, mendixIdentifier);
	}

	/**
	 * Initialize a proxy using context (recommended). This context will be used for security checking when the get- and set-methods without context parameters are called.
	 * The get- and set-methods with context parameter should be used when for instance sudo access is necessary (IContext.createSudoClone() can be used to obtain sudo access).
	 */
	public static migrationutility.proxies.DataStats_Before initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject mendixObject)
	{
		return new migrationutility.proxies.DataStats_Before(context, mendixObject);
	}

	public static migrationutility.proxies.DataStats_Before load(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		com.mendix.systemwideinterfaces.core.IMendixObject mendixObject = com.mendix.core.Core.retrieveId(context, mendixIdentifier);
		return migrationutility.proxies.DataStats_Before.initialize(context, mendixObject);
	}

	public static java.util.List<migrationutility.proxies.DataStats_Before> load(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String xpathConstraint) throws com.mendix.core.CoreException
	{
		java.util.List<migrationutility.proxies.DataStats_Before> result = new java.util.ArrayList<migrationutility.proxies.DataStats_Before>();
		for (com.mendix.systemwideinterfaces.core.IMendixObject obj : com.mendix.core.Core.retrieveXPathQuery(context, "//MigrationUtility.DataStats_Before" + xpathConstraint))
			result.add(migrationutility.proxies.DataStats_Before.initialize(context, obj));
		return result;
	}

	/**
	 * Commit the changes made on this proxy object.
	 */
	public final void commit() throws com.mendix.core.CoreException
	{
		com.mendix.core.Core.commit(context, getMendixObject());
	}

	/**
	 * Commit the changes made on this proxy object using the specified context.
	 */
	public final void commit(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		com.mendix.core.Core.commit(context, getMendixObject());
	}

	/**
	 * Delete the object.
	 */
	public final void delete()
	{
		com.mendix.core.Core.delete(context, getMendixObject());
	}

	/**
	 * Delete the object using the specified context.
	 */
	public final void delete(com.mendix.systemwideinterfaces.core.IContext context)
	{
		com.mendix.core.Core.delete(context, getMendixObject());
	}
	/**
	 * @return value of ECAccounts
	 */
	public final java.lang.Long getECAccounts()
	{
		return getECAccounts(getContext());
	}

	/**
	 * @param context
	 * @return value of ECAccounts
	 */
	public final java.lang.Long getECAccounts(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.Long) getMendixObject().getValue(context, MemberNames.ECAccounts.toString());
	}

	/**
	 * Set value of ECAccounts
	 * @param ecaccounts
	 */
	public final void setECAccounts(java.lang.Long ecaccounts)
	{
		setECAccounts(getContext(), ecaccounts);
	}

	/**
	 * Set value of ECAccounts
	 * @param context
	 * @param ecaccounts
	 */
	public final void setECAccounts(com.mendix.systemwideinterfaces.core.IContext context, java.lang.Long ecaccounts)
	{
		getMendixObject().setValue(context, MemberNames.ECAccounts.toString(), ecaccounts);
	}

	/**
	 * @return value of ECEmails
	 */
	public final java.lang.Long getECEmails()
	{
		return getECEmails(getContext());
	}

	/**
	 * @param context
	 * @return value of ECEmails
	 */
	public final java.lang.Long getECEmails(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.Long) getMendixObject().getValue(context, MemberNames.ECEmails.toString());
	}

	/**
	 * Set value of ECEmails
	 * @param ecemails
	 */
	public final void setECEmails(java.lang.Long ecemails)
	{
		setECEmails(getContext(), ecemails);
	}

	/**
	 * Set value of ECEmails
	 * @param context
	 * @param ecemails
	 */
	public final void setECEmails(com.mendix.systemwideinterfaces.core.IContext context, java.lang.Long ecemails)
	{
		getMendixObject().setValue(context, MemberNames.ECEmails.toString(), ecemails);
	}

	/**
	 * @return value of ECTemplates
	 */
	public final java.lang.Long getECTemplates()
	{
		return getECTemplates(getContext());
	}

	/**
	 * @param context
	 * @return value of ECTemplates
	 */
	public final java.lang.Long getECTemplates(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.Long) getMendixObject().getValue(context, MemberNames.ECTemplates.toString());
	}

	/**
	 * Set value of ECTemplates
	 * @param ectemplates
	 */
	public final void setECTemplates(java.lang.Long ectemplates)
	{
		setECTemplates(getContext(), ectemplates);
	}

	/**
	 * Set value of ECTemplates
	 * @param context
	 * @param ectemplates
	 */
	public final void setECTemplates(com.mendix.systemwideinterfaces.core.IContext context, java.lang.Long ectemplates)
	{
		getMendixObject().setValue(context, MemberNames.ECTemplates.toString(), ectemplates);
	}

	/**
	 * @return value of ECErrorLogs
	 */
	public final java.lang.Long getECErrorLogs()
	{
		return getECErrorLogs(getContext());
	}

	/**
	 * @param context
	 * @return value of ECErrorLogs
	 */
	public final java.lang.Long getECErrorLogs(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.Long) getMendixObject().getValue(context, MemberNames.ECErrorLogs.toString());
	}

	/**
	 * Set value of ECErrorLogs
	 * @param ecerrorlogs
	 */
	public final void setECErrorLogs(java.lang.Long ecerrorlogs)
	{
		setECErrorLogs(getContext(), ecerrorlogs);
	}

	/**
	 * Set value of ECErrorLogs
	 * @param context
	 * @param ecerrorlogs
	 */
	public final void setECErrorLogs(com.mendix.systemwideinterfaces.core.IContext context, java.lang.Long ecerrorlogs)
	{
		getMendixObject().setValue(context, MemberNames.ECErrorLogs.toString(), ecerrorlogs);
	}

	/**
	 * @return value of ETAccounts
	 */
	public final java.lang.Long getETAccounts()
	{
		return getETAccounts(getContext());
	}

	/**
	 * @param context
	 * @return value of ETAccounts
	 */
	public final java.lang.Long getETAccounts(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.Long) getMendixObject().getValue(context, MemberNames.ETAccounts.toString());
	}

	/**
	 * Set value of ETAccounts
	 * @param etaccounts
	 */
	public final void setETAccounts(java.lang.Long etaccounts)
	{
		setETAccounts(getContext(), etaccounts);
	}

	/**
	 * Set value of ETAccounts
	 * @param context
	 * @param etaccounts
	 */
	public final void setETAccounts(com.mendix.systemwideinterfaces.core.IContext context, java.lang.Long etaccounts)
	{
		getMendixObject().setValue(context, MemberNames.ETAccounts.toString(), etaccounts);
	}

	/**
	 * @return value of ETEmails
	 */
	public final java.lang.Long getETEmails()
	{
		return getETEmails(getContext());
	}

	/**
	 * @param context
	 * @return value of ETEmails
	 */
	public final java.lang.Long getETEmails(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.Long) getMendixObject().getValue(context, MemberNames.ETEmails.toString());
	}

	/**
	 * Set value of ETEmails
	 * @param etemails
	 */
	public final void setETEmails(java.lang.Long etemails)
	{
		setETEmails(getContext(), etemails);
	}

	/**
	 * Set value of ETEmails
	 * @param context
	 * @param etemails
	 */
	public final void setETEmails(com.mendix.systemwideinterfaces.core.IContext context, java.lang.Long etemails)
	{
		getMendixObject().setValue(context, MemberNames.ETEmails.toString(), etemails);
	}

	/**
	 * @return value of ETTemplates
	 */
	public final java.lang.Long getETTemplates()
	{
		return getETTemplates(getContext());
	}

	/**
	 * @param context
	 * @return value of ETTemplates
	 */
	public final java.lang.Long getETTemplates(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.Long) getMendixObject().getValue(context, MemberNames.ETTemplates.toString());
	}

	/**
	 * Set value of ETTemplates
	 * @param ettemplates
	 */
	public final void setETTemplates(java.lang.Long ettemplates)
	{
		setETTemplates(getContext(), ettemplates);
	}

	/**
	 * Set value of ETTemplates
	 * @param context
	 * @param ettemplates
	 */
	public final void setETTemplates(com.mendix.systemwideinterfaces.core.IContext context, java.lang.Long ettemplates)
	{
		getMendixObject().setValue(context, MemberNames.ETTemplates.toString(), ettemplates);
	}

	/**
	 * @return value of ETErrorLogs
	 */
	public final java.lang.Long getETErrorLogs()
	{
		return getETErrorLogs(getContext());
	}

	/**
	 * @param context
	 * @return value of ETErrorLogs
	 */
	public final java.lang.Long getETErrorLogs(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.Long) getMendixObject().getValue(context, MemberNames.ETErrorLogs.toString());
	}

	/**
	 * Set value of ETErrorLogs
	 * @param eterrorlogs
	 */
	public final void setETErrorLogs(java.lang.Long eterrorlogs)
	{
		setETErrorLogs(getContext(), eterrorlogs);
	}

	/**
	 * Set value of ETErrorLogs
	 * @param context
	 * @param eterrorlogs
	 */
	public final void setETErrorLogs(com.mendix.systemwideinterfaces.core.IContext context, java.lang.Long eterrorlogs)
	{
		getMendixObject().setValue(context, MemberNames.ETErrorLogs.toString(), eterrorlogs);
	}

	/**
	 * @return the IMendixObject instance of this proxy for use in the Core interface.
	 */
	public final com.mendix.systemwideinterfaces.core.IMendixObject getMendixObject()
	{
		return dataStats_BeforeMendixObject;
	}

	/**
	 * @return the IContext instance of this proxy, or null if no IContext instance was specified at initialization.
	 */
	public final com.mendix.systemwideinterfaces.core.IContext getContext()
	{
		return context;
	}

	@java.lang.Override
	public boolean equals(Object obj)
	{
		if (obj == this)
			return true;

		if (obj != null && getClass().equals(obj.getClass()))
		{
			final migrationutility.proxies.DataStats_Before that = (migrationutility.proxies.DataStats_Before) obj;
			return getMendixObject().equals(that.getMendixObject());
		}
		return false;
	}

	@java.lang.Override
	public int hashCode()
	{
		return getMendixObject().hashCode();
	}

	/**
	 * @return String name of this class
	 */
	public static java.lang.String getType()
	{
		return "MigrationUtility.DataStats_Before";
	}

	/**
	 * @return String GUID from this object, format: ID_0000000000
	 * @deprecated Use getMendixObject().getId().toLong() to get a unique identifier for this object.
	 */
	@java.lang.Deprecated
	public java.lang.String getGUID()
	{
		return "ID_" + getMendixObject().getId().toLong();
	}
}
