// This file was generated by Mendix Studio Pro.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package migrationutility.proxies;

public class ECDataStats_After
{
	private final com.mendix.systemwideinterfaces.core.IMendixObject eCDataStats_AfterMendixObject;

	private final com.mendix.systemwideinterfaces.core.IContext context;

	/**
	 * Internal name of this entity
	 */
	public static final java.lang.String entityName = "MigrationUtility.ECDataStats_After";

	/**
	 * Enum describing members of this entity
	 */
	public enum MemberNames
	{
		NrOfAccounts("NrOfAccounts"),
		NrOfEmails("NrOfEmails"),
		NrOfTemplates("NrOfTemplates"),
		NrOfErrorLogs("NrOfErrorLogs");

		private java.lang.String metaName;

		MemberNames(java.lang.String s)
		{
			metaName = s;
		}

		@java.lang.Override
		public java.lang.String toString()
		{
			return metaName;
		}
	}

	public ECDataStats_After(com.mendix.systemwideinterfaces.core.IContext context)
	{
		this(context, com.mendix.core.Core.instantiate(context, "MigrationUtility.ECDataStats_After"));
	}

	protected ECDataStats_After(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject eCDataStats_AfterMendixObject)
	{
		if (eCDataStats_AfterMendixObject == null)
			throw new java.lang.IllegalArgumentException("The given object cannot be null.");
		if (!com.mendix.core.Core.isSubClassOf("MigrationUtility.ECDataStats_After", eCDataStats_AfterMendixObject.getType()))
			throw new java.lang.IllegalArgumentException("The given object is not a MigrationUtility.ECDataStats_After");

		this.eCDataStats_AfterMendixObject = eCDataStats_AfterMendixObject;
		this.context = context;
	}

	/**
	 * @deprecated Use 'ECDataStats_After.load(IContext, IMendixIdentifier)' instead.
	 */
	@java.lang.Deprecated
	public static migrationutility.proxies.ECDataStats_After initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		return migrationutility.proxies.ECDataStats_After.load(context, mendixIdentifier);
	}

	/**
	 * Initialize a proxy using context (recommended). This context will be used for security checking when the get- and set-methods without context parameters are called.
	 * The get- and set-methods with context parameter should be used when for instance sudo access is necessary (IContext.createSudoClone() can be used to obtain sudo access).
	 */
	public static migrationutility.proxies.ECDataStats_After initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject mendixObject)
	{
		return new migrationutility.proxies.ECDataStats_After(context, mendixObject);
	}

	public static migrationutility.proxies.ECDataStats_After load(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		com.mendix.systemwideinterfaces.core.IMendixObject mendixObject = com.mendix.core.Core.retrieveId(context, mendixIdentifier);
		return migrationutility.proxies.ECDataStats_After.initialize(context, mendixObject);
	}

	/**
	 * Commit the changes made on this proxy object.
	 */
	public final void commit() throws com.mendix.core.CoreException
	{
		com.mendix.core.Core.commit(context, getMendixObject());
	}

	/**
	 * Commit the changes made on this proxy object using the specified context.
	 */
	public final void commit(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		com.mendix.core.Core.commit(context, getMendixObject());
	}

	/**
	 * Delete the object.
	 */
	public final void delete()
	{
		com.mendix.core.Core.delete(context, getMendixObject());
	}

	/**
	 * Delete the object using the specified context.
	 */
	public final void delete(com.mendix.systemwideinterfaces.core.IContext context)
	{
		com.mendix.core.Core.delete(context, getMendixObject());
	}
	/**
	 * @return value of NrOfAccounts
	 */
	public final java.lang.Long getNrOfAccounts()
	{
		return getNrOfAccounts(getContext());
	}

	/**
	 * @param context
	 * @return value of NrOfAccounts
	 */
	public final java.lang.Long getNrOfAccounts(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.Long) getMendixObject().getValue(context, MemberNames.NrOfAccounts.toString());
	}

	/**
	 * Set value of NrOfAccounts
	 * @param nrofaccounts
	 */
	public final void setNrOfAccounts(java.lang.Long nrofaccounts)
	{
		setNrOfAccounts(getContext(), nrofaccounts);
	}

	/**
	 * Set value of NrOfAccounts
	 * @param context
	 * @param nrofaccounts
	 */
	public final void setNrOfAccounts(com.mendix.systemwideinterfaces.core.IContext context, java.lang.Long nrofaccounts)
	{
		getMendixObject().setValue(context, MemberNames.NrOfAccounts.toString(), nrofaccounts);
	}

	/**
	 * @return value of NrOfEmails
	 */
	public final java.lang.Long getNrOfEmails()
	{
		return getNrOfEmails(getContext());
	}

	/**
	 * @param context
	 * @return value of NrOfEmails
	 */
	public final java.lang.Long getNrOfEmails(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.Long) getMendixObject().getValue(context, MemberNames.NrOfEmails.toString());
	}

	/**
	 * Set value of NrOfEmails
	 * @param nrofemails
	 */
	public final void setNrOfEmails(java.lang.Long nrofemails)
	{
		setNrOfEmails(getContext(), nrofemails);
	}

	/**
	 * Set value of NrOfEmails
	 * @param context
	 * @param nrofemails
	 */
	public final void setNrOfEmails(com.mendix.systemwideinterfaces.core.IContext context, java.lang.Long nrofemails)
	{
		getMendixObject().setValue(context, MemberNames.NrOfEmails.toString(), nrofemails);
	}

	/**
	 * @return value of NrOfTemplates
	 */
	public final java.lang.Long getNrOfTemplates()
	{
		return getNrOfTemplates(getContext());
	}

	/**
	 * @param context
	 * @return value of NrOfTemplates
	 */
	public final java.lang.Long getNrOfTemplates(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.Long) getMendixObject().getValue(context, MemberNames.NrOfTemplates.toString());
	}

	/**
	 * Set value of NrOfTemplates
	 * @param nroftemplates
	 */
	public final void setNrOfTemplates(java.lang.Long nroftemplates)
	{
		setNrOfTemplates(getContext(), nroftemplates);
	}

	/**
	 * Set value of NrOfTemplates
	 * @param context
	 * @param nroftemplates
	 */
	public final void setNrOfTemplates(com.mendix.systemwideinterfaces.core.IContext context, java.lang.Long nroftemplates)
	{
		getMendixObject().setValue(context, MemberNames.NrOfTemplates.toString(), nroftemplates);
	}

	/**
	 * @return value of NrOfErrorLogs
	 */
	public final java.lang.Long getNrOfErrorLogs()
	{
		return getNrOfErrorLogs(getContext());
	}

	/**
	 * @param context
	 * @return value of NrOfErrorLogs
	 */
	public final java.lang.Long getNrOfErrorLogs(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.Long) getMendixObject().getValue(context, MemberNames.NrOfErrorLogs.toString());
	}

	/**
	 * Set value of NrOfErrorLogs
	 * @param nroferrorlogs
	 */
	public final void setNrOfErrorLogs(java.lang.Long nroferrorlogs)
	{
		setNrOfErrorLogs(getContext(), nroferrorlogs);
	}

	/**
	 * Set value of NrOfErrorLogs
	 * @param context
	 * @param nroferrorlogs
	 */
	public final void setNrOfErrorLogs(com.mendix.systemwideinterfaces.core.IContext context, java.lang.Long nroferrorlogs)
	{
		getMendixObject().setValue(context, MemberNames.NrOfErrorLogs.toString(), nroferrorlogs);
	}

	/**
	 * @return the IMendixObject instance of this proxy for use in the Core interface.
	 */
	public final com.mendix.systemwideinterfaces.core.IMendixObject getMendixObject()
	{
		return eCDataStats_AfterMendixObject;
	}

	/**
	 * @return the IContext instance of this proxy, or null if no IContext instance was specified at initialization.
	 */
	public final com.mendix.systemwideinterfaces.core.IContext getContext()
	{
		return context;
	}

	@java.lang.Override
	public boolean equals(Object obj)
	{
		if (obj == this)
			return true;

		if (obj != null && getClass().equals(obj.getClass()))
		{
			final migrationutility.proxies.ECDataStats_After that = (migrationutility.proxies.ECDataStats_After) obj;
			return getMendixObject().equals(that.getMendixObject());
		}
		return false;
	}

	@java.lang.Override
	public int hashCode()
	{
		return getMendixObject().hashCode();
	}

	/**
	 * @return String name of this class
	 */
	public static java.lang.String getType()
	{
		return "MigrationUtility.ECDataStats_After";
	}

	/**
	 * @return String GUID from this object, format: ID_0000000000
	 * @deprecated Use getMendixObject().getId().toLong() to get a unique identifier for this object.
	 */
	@java.lang.Deprecated
	public java.lang.String getGUID()
	{
		return "ID_" + getMendixObject().getId().toLong();
	}
}
