// This file was generated by Mendix Studio Pro.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package migrationutility.proxies;

public class MigrationConfig
{
	private final com.mendix.systemwideinterfaces.core.IMendixObject migrationConfigMendixObject;

	private final com.mendix.systemwideinterfaces.core.IContext context;

	/**
	 * Internal name of this entity
	 */
	public static final java.lang.String entityName = "MigrationUtility.MigrationConfig";

	/**
	 * Enum describing members of this entity
	 */
	public enum MemberNames
	{
		MigrateAccounts("MigrateAccounts"),
		MigrateEmailTemplates("MigrateEmailTemplates"),
		MigrateEmails("MigrateEmails"),
		MigrateErrorLogs("MigrateErrorLogs");

		private java.lang.String metaName;

		MemberNames(java.lang.String s)
		{
			metaName = s;
		}

		@java.lang.Override
		public java.lang.String toString()
		{
			return metaName;
		}
	}

	public MigrationConfig(com.mendix.systemwideinterfaces.core.IContext context)
	{
		this(context, com.mendix.core.Core.instantiate(context, "MigrationUtility.MigrationConfig"));
	}

	protected MigrationConfig(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject migrationConfigMendixObject)
	{
		if (migrationConfigMendixObject == null)
			throw new java.lang.IllegalArgumentException("The given object cannot be null.");
		if (!com.mendix.core.Core.isSubClassOf("MigrationUtility.MigrationConfig", migrationConfigMendixObject.getType()))
			throw new java.lang.IllegalArgumentException("The given object is not a MigrationUtility.MigrationConfig");

		this.migrationConfigMendixObject = migrationConfigMendixObject;
		this.context = context;
	}

	/**
	 * @deprecated Use 'MigrationConfig.load(IContext, IMendixIdentifier)' instead.
	 */
	@java.lang.Deprecated
	public static migrationutility.proxies.MigrationConfig initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		return migrationutility.proxies.MigrationConfig.load(context, mendixIdentifier);
	}

	/**
	 * Initialize a proxy using context (recommended). This context will be used for security checking when the get- and set-methods without context parameters are called.
	 * The get- and set-methods with context parameter should be used when for instance sudo access is necessary (IContext.createSudoClone() can be used to obtain sudo access).
	 */
	public static migrationutility.proxies.MigrationConfig initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject mendixObject)
	{
		return new migrationutility.proxies.MigrationConfig(context, mendixObject);
	}

	public static migrationutility.proxies.MigrationConfig load(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		com.mendix.systemwideinterfaces.core.IMendixObject mendixObject = com.mendix.core.Core.retrieveId(context, mendixIdentifier);
		return migrationutility.proxies.MigrationConfig.initialize(context, mendixObject);
	}

	/**
	 * Commit the changes made on this proxy object.
	 */
	public final void commit() throws com.mendix.core.CoreException
	{
		com.mendix.core.Core.commit(context, getMendixObject());
	}

	/**
	 * Commit the changes made on this proxy object using the specified context.
	 */
	public final void commit(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		com.mendix.core.Core.commit(context, getMendixObject());
	}

	/**
	 * Delete the object.
	 */
	public final void delete()
	{
		com.mendix.core.Core.delete(context, getMendixObject());
	}

	/**
	 * Delete the object using the specified context.
	 */
	public final void delete(com.mendix.systemwideinterfaces.core.IContext context)
	{
		com.mendix.core.Core.delete(context, getMendixObject());
	}
	/**
	 * @return value of MigrateAccounts
	 */
	public final java.lang.Boolean getMigrateAccounts()
	{
		return getMigrateAccounts(getContext());
	}

	/**
	 * @param context
	 * @return value of MigrateAccounts
	 */
	public final java.lang.Boolean getMigrateAccounts(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.Boolean) getMendixObject().getValue(context, MemberNames.MigrateAccounts.toString());
	}

	/**
	 * Set value of MigrateAccounts
	 * @param migrateaccounts
	 */
	public final void setMigrateAccounts(java.lang.Boolean migrateaccounts)
	{
		setMigrateAccounts(getContext(), migrateaccounts);
	}

	/**
	 * Set value of MigrateAccounts
	 * @param context
	 * @param migrateaccounts
	 */
	public final void setMigrateAccounts(com.mendix.systemwideinterfaces.core.IContext context, java.lang.Boolean migrateaccounts)
	{
		getMendixObject().setValue(context, MemberNames.MigrateAccounts.toString(), migrateaccounts);
	}

	/**
	 * @return value of MigrateEmailTemplates
	 */
	public final java.lang.Boolean getMigrateEmailTemplates()
	{
		return getMigrateEmailTemplates(getContext());
	}

	/**
	 * @param context
	 * @return value of MigrateEmailTemplates
	 */
	public final java.lang.Boolean getMigrateEmailTemplates(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.Boolean) getMendixObject().getValue(context, MemberNames.MigrateEmailTemplates.toString());
	}

	/**
	 * Set value of MigrateEmailTemplates
	 * @param migrateemailtemplates
	 */
	public final void setMigrateEmailTemplates(java.lang.Boolean migrateemailtemplates)
	{
		setMigrateEmailTemplates(getContext(), migrateemailtemplates);
	}

	/**
	 * Set value of MigrateEmailTemplates
	 * @param context
	 * @param migrateemailtemplates
	 */
	public final void setMigrateEmailTemplates(com.mendix.systemwideinterfaces.core.IContext context, java.lang.Boolean migrateemailtemplates)
	{
		getMendixObject().setValue(context, MemberNames.MigrateEmailTemplates.toString(), migrateemailtemplates);
	}

	/**
	 * @return value of MigrateEmails
	 */
	public final java.lang.Boolean getMigrateEmails()
	{
		return getMigrateEmails(getContext());
	}

	/**
	 * @param context
	 * @return value of MigrateEmails
	 */
	public final java.lang.Boolean getMigrateEmails(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.Boolean) getMendixObject().getValue(context, MemberNames.MigrateEmails.toString());
	}

	/**
	 * Set value of MigrateEmails
	 * @param migrateemails
	 */
	public final void setMigrateEmails(java.lang.Boolean migrateemails)
	{
		setMigrateEmails(getContext(), migrateemails);
	}

	/**
	 * Set value of MigrateEmails
	 * @param context
	 * @param migrateemails
	 */
	public final void setMigrateEmails(com.mendix.systemwideinterfaces.core.IContext context, java.lang.Boolean migrateemails)
	{
		getMendixObject().setValue(context, MemberNames.MigrateEmails.toString(), migrateemails);
	}

	/**
	 * @return value of MigrateErrorLogs
	 */
	public final java.lang.Boolean getMigrateErrorLogs()
	{
		return getMigrateErrorLogs(getContext());
	}

	/**
	 * @param context
	 * @return value of MigrateErrorLogs
	 */
	public final java.lang.Boolean getMigrateErrorLogs(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.Boolean) getMendixObject().getValue(context, MemberNames.MigrateErrorLogs.toString());
	}

	/**
	 * Set value of MigrateErrorLogs
	 * @param migrateerrorlogs
	 */
	public final void setMigrateErrorLogs(java.lang.Boolean migrateerrorlogs)
	{
		setMigrateErrorLogs(getContext(), migrateerrorlogs);
	}

	/**
	 * Set value of MigrateErrorLogs
	 * @param context
	 * @param migrateerrorlogs
	 */
	public final void setMigrateErrorLogs(com.mendix.systemwideinterfaces.core.IContext context, java.lang.Boolean migrateerrorlogs)
	{
		getMendixObject().setValue(context, MemberNames.MigrateErrorLogs.toString(), migrateerrorlogs);
	}

	/**
	 * @return the IMendixObject instance of this proxy for use in the Core interface.
	 */
	public final com.mendix.systemwideinterfaces.core.IMendixObject getMendixObject()
	{
		return migrationConfigMendixObject;
	}

	/**
	 * @return the IContext instance of this proxy, or null if no IContext instance was specified at initialization.
	 */
	public final com.mendix.systemwideinterfaces.core.IContext getContext()
	{
		return context;
	}

	@java.lang.Override
	public boolean equals(Object obj)
	{
		if (obj == this)
			return true;

		if (obj != null && getClass().equals(obj.getClass()))
		{
			final migrationutility.proxies.MigrationConfig that = (migrationutility.proxies.MigrationConfig) obj;
			return getMendixObject().equals(that.getMendixObject());
		}
		return false;
	}

	@java.lang.Override
	public int hashCode()
	{
		return getMendixObject().hashCode();
	}

	/**
	 * @return String name of this class
	 */
	public static java.lang.String getType()
	{
		return "MigrationUtility.MigrationConfig";
	}

	/**
	 * @return String GUID from this object, format: ID_0000000000
	 * @deprecated Use getMendixObject().getId().toLong() to get a unique identifier for this object.
	 */
	@java.lang.Deprecated
	public java.lang.String getGUID()
	{
		return "ID_" + getMendixObject().getId().toLong();
	}
}
