// This file was generated by Mendix Studio Pro.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package migrationutility.proxies.microflows;

import java.util.HashMap;
import java.util.Map;
import com.mendix.core.Core;
import com.mendix.core.CoreException;
import com.mendix.systemwideinterfaces.MendixRuntimeException;
import com.mendix.systemwideinterfaces.core.IContext;
import com.mendix.systemwideinterfaces.core.IMendixObject;

public class Microflows
{
	// These are the microflows for the MigrationUtility module
	public static void aCT_DeleteBeforeStats(IContext context, migrationutility.proxies.DataStats_Before _dataStats_Before)
	{
		Map<java.lang.String, Object> params = new HashMap<>();
		params.put("DataStats_Before", _dataStats_Before == null ? null : _dataStats_Before.getMendixObject());
		Core.microflowCall("MigrationUtility.ACT_DeleteBeforeStats").withParams(params).execute(context);
	}
	public static void aCT_ExportEmailAccounts(IContext context)
	{
		Map<java.lang.String, Object> params = new HashMap<>();
		Core.microflowCall("MigrationUtility.ACT_ExportEmailAccounts").withParams(params).execute(context);
	}
	public static void aCT_ExportEmailTemplates(IContext context)
	{
		Map<java.lang.String, Object> params = new HashMap<>();
		Core.microflowCall("MigrationUtility.ACT_ExportEmailTemplates").withParams(params).execute(context);
	}
	public static void aCT_ExportErrorLog(IContext context)
	{
		Map<java.lang.String, Object> params = new HashMap<>();
		Core.microflowCall("MigrationUtility.ACT_ExportErrorLog").withParams(params).execute(context);
	}
	public static void aCT_StartMigration(IContext context, migrationutility.proxies.MigrationConfig _migrationConfig)
	{
		Map<java.lang.String, Object> params = new HashMap<>();
		params.put("MigrationConfig", _migrationConfig == null ? null : _migrationConfig.getMendixObject());
		Core.microflowCall("MigrationUtility.ACT_StartMigration").withParams(params).execute(context);
	}
	public static java.lang.String cVRT_TruncateEmailLogMessage(IContext context, java.lang.String _message)
	{
		Map<java.lang.String, Object> params = new HashMap<>();
		params.put("Message", _message);
		return (java.lang.String) Core.microflowCall("MigrationUtility.CVRT_TruncateEmailLogMessage").withParams(params).execute(context);
	}
	public static migrationutility.proxies.DataStats_Before dS_BeforeStats(IContext context)
	{
		Map<java.lang.String, Object> params = new HashMap<>();
		IMendixObject result = (IMendixObject)Core.microflowCall("MigrationUtility.DS_BeforeStats").withParams(params).execute(context);
		return result == null ? null : migrationutility.proxies.DataStats_Before.initialize(context, result);
	}
	public static migrationutility.proxies.MigrationConfig dS_MigrationConfig(IContext context)
	{
		Map<java.lang.String, Object> params = new HashMap<>();
		IMendixObject result = (IMendixObject)Core.microflowCall("MigrationUtility.DS_MigrationConfig").withParams(params).execute(context);
		return result == null ? null : migrationutility.proxies.MigrationConfig.initialize(context, result);
	}
}