// This file was generated by Mendix Studio Pro.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package email_connector.proxies;

public class OAuthError
{
	private final com.mendix.systemwideinterfaces.core.IMendixObject oAuthErrorMendixObject;

	private final com.mendix.systemwideinterfaces.core.IContext context;

	/**
	 * Internal name of this entity
	 */
	public static final java.lang.String entityName = "Email_Connector.OAuthError";

	/**
	 * Enum describing members of this entity
	 */
	public enum MemberNames
	{
		HTTPStatusCode("HTTPStatusCode"),
		Error("Error"),
		OAuthError_Session("Email_Connector.OAuthError_Session");

		private java.lang.String metaName;

		MemberNames(java.lang.String s)
		{
			metaName = s;
		}

		@java.lang.Override
		public java.lang.String toString()
		{
			return metaName;
		}
	}

	public OAuthError(com.mendix.systemwideinterfaces.core.IContext context)
	{
		this(context, com.mendix.core.Core.instantiate(context, "Email_Connector.OAuthError"));
	}

	protected OAuthError(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject oAuthErrorMendixObject)
	{
		if (oAuthErrorMendixObject == null)
			throw new java.lang.IllegalArgumentException("The given object cannot be null.");
		if (!com.mendix.core.Core.isSubClassOf("Email_Connector.OAuthError", oAuthErrorMendixObject.getType()))
			throw new java.lang.IllegalArgumentException("The given object is not a Email_Connector.OAuthError");

		this.oAuthErrorMendixObject = oAuthErrorMendixObject;
		this.context = context;
	}

	/**
	 * @deprecated Use 'OAuthError.load(IContext, IMendixIdentifier)' instead.
	 */
	@java.lang.Deprecated
	public static email_connector.proxies.OAuthError initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		return email_connector.proxies.OAuthError.load(context, mendixIdentifier);
	}

	/**
	 * Initialize a proxy using context (recommended). This context will be used for security checking when the get- and set-methods without context parameters are called.
	 * The get- and set-methods with context parameter should be used when for instance sudo access is necessary (IContext.createSudoClone() can be used to obtain sudo access).
	 */
	public static email_connector.proxies.OAuthError initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject mendixObject)
	{
		return new email_connector.proxies.OAuthError(context, mendixObject);
	}

	public static email_connector.proxies.OAuthError load(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		com.mendix.systemwideinterfaces.core.IMendixObject mendixObject = com.mendix.core.Core.retrieveId(context, mendixIdentifier);
		return email_connector.proxies.OAuthError.initialize(context, mendixObject);
	}

	public static java.util.List<email_connector.proxies.OAuthError> load(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String xpathConstraint) throws com.mendix.core.CoreException
	{
		java.util.List<email_connector.proxies.OAuthError> result = new java.util.ArrayList<email_connector.proxies.OAuthError>();
		for (com.mendix.systemwideinterfaces.core.IMendixObject obj : com.mendix.core.Core.retrieveXPathQuery(context, "//Email_Connector.OAuthError" + xpathConstraint))
			result.add(email_connector.proxies.OAuthError.initialize(context, obj));
		return result;
	}

	/**
	 * Commit the changes made on this proxy object.
	 */
	public final void commit() throws com.mendix.core.CoreException
	{
		com.mendix.core.Core.commit(context, getMendixObject());
	}

	/**
	 * Commit the changes made on this proxy object using the specified context.
	 */
	public final void commit(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		com.mendix.core.Core.commit(context, getMendixObject());
	}

	/**
	 * Delete the object.
	 */
	public final void delete()
	{
		com.mendix.core.Core.delete(context, getMendixObject());
	}

	/**
	 * Delete the object using the specified context.
	 */
	public final void delete(com.mendix.systemwideinterfaces.core.IContext context)
	{
		com.mendix.core.Core.delete(context, getMendixObject());
	}
	/**
	 * @return value of HTTPStatusCode
	 */
	public final java.lang.Integer getHTTPStatusCode()
	{
		return getHTTPStatusCode(getContext());
	}

	/**
	 * @param context
	 * @return value of HTTPStatusCode
	 */
	public final java.lang.Integer getHTTPStatusCode(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.Integer) getMendixObject().getValue(context, MemberNames.HTTPStatusCode.toString());
	}

	/**
	 * Set value of HTTPStatusCode
	 * @param httpstatuscode
	 */
	public final void setHTTPStatusCode(java.lang.Integer httpstatuscode)
	{
		setHTTPStatusCode(getContext(), httpstatuscode);
	}

	/**
	 * Set value of HTTPStatusCode
	 * @param context
	 * @param httpstatuscode
	 */
	public final void setHTTPStatusCode(com.mendix.systemwideinterfaces.core.IContext context, java.lang.Integer httpstatuscode)
	{
		getMendixObject().setValue(context, MemberNames.HTTPStatusCode.toString(), httpstatuscode);
	}

	/**
	 * @return value of Error
	 */
	public final java.lang.String getError()
	{
		return getError(getContext());
	}

	/**
	 * @param context
	 * @return value of Error
	 */
	public final java.lang.String getError(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.Error.toString());
	}

	/**
	 * Set value of Error
	 * @param error
	 */
	public final void setError(java.lang.String error)
	{
		setError(getContext(), error);
	}

	/**
	 * Set value of Error
	 * @param context
	 * @param error
	 */
	public final void setError(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String error)
	{
		getMendixObject().setValue(context, MemberNames.Error.toString(), error);
	}

	/**
	 * @return value of OAuthError_Session
	 */
	public final system.proxies.Session getOAuthError_Session() throws com.mendix.core.CoreException
	{
		return getOAuthError_Session(getContext());
	}

	/**
	 * @param context
	 * @return value of OAuthError_Session
	 */
	public final system.proxies.Session getOAuthError_Session(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		system.proxies.Session result = null;
		com.mendix.systemwideinterfaces.core.IMendixIdentifier identifier = getMendixObject().getValue(context, MemberNames.OAuthError_Session.toString());
		if (identifier != null)
			result = system.proxies.Session.load(context, identifier);
		return result;
	}

	/**
	 * Set value of OAuthError_Session
	 * @param oautherror_session
	 */
	public final void setOAuthError_Session(system.proxies.Session oautherror_session)
	{
		setOAuthError_Session(getContext(), oautherror_session);
	}

	/**
	 * Set value of OAuthError_Session
	 * @param context
	 * @param oautherror_session
	 */
	public final void setOAuthError_Session(com.mendix.systemwideinterfaces.core.IContext context, system.proxies.Session oautherror_session)
	{
		if (oautherror_session == null)
			getMendixObject().setValue(context, MemberNames.OAuthError_Session.toString(), null);
		else
			getMendixObject().setValue(context, MemberNames.OAuthError_Session.toString(), oautherror_session.getMendixObject().getId());
	}

	/**
	 * @return the IMendixObject instance of this proxy for use in the Core interface.
	 */
	public final com.mendix.systemwideinterfaces.core.IMendixObject getMendixObject()
	{
		return oAuthErrorMendixObject;
	}

	/**
	 * @return the IContext instance of this proxy, or null if no IContext instance was specified at initialization.
	 */
	public final com.mendix.systemwideinterfaces.core.IContext getContext()
	{
		return context;
	}

	@java.lang.Override
	public boolean equals(Object obj)
	{
		if (obj == this)
			return true;

		if (obj != null && getClass().equals(obj.getClass()))
		{
			final email_connector.proxies.OAuthError that = (email_connector.proxies.OAuthError) obj;
			return getMendixObject().equals(that.getMendixObject());
		}
		return false;
	}

	@java.lang.Override
	public int hashCode()
	{
		return getMendixObject().hashCode();
	}

	/**
	 * @return String name of this class
	 */
	public static java.lang.String getType()
	{
		return "Email_Connector.OAuthError";
	}

	/**
	 * @return String GUID from this object, format: ID_0000000000
	 * @deprecated Use getMendixObject().getId().toLong() to get a unique identifier for this object.
	 */
	@java.lang.Deprecated
	public java.lang.String getGUID()
	{
		return "ID_" + getMendixObject().getId().toLong();
	}
}
